# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
env:
  global:
    - EXAMPLE="Example"
    - CI_HOME=$TRAVIS_BUILD_DIR/$EXAMPLE
install:
#- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- brew install xctool
- pod install
script:
- set -o pipefail && xctool test -workspace BugReportKit.xcworkspace -scheme BugReportKit_Tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
